apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: grafana-http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer